InnovaGameCreate/akumutogenjitsu

- .github/workflows/ai-review.yaml
- Assets/Scenes/DeveloppingScenes/Enemy.unity
- Assets/Scenes/DeveloppingScenes/Enemy.unity.meta
- Assets/Scripts/GameScene/Unit/AbstractUnitController.cs
- Assets/Scripts/GameScene/Unit/Enemy.meta
- Assets/Scripts/GameScene/Unit/Enemy/EnemyDamagePlayer.cs
- Assets/Scripts/GameScene/Unit/Enemy/EnemyDamagePlayer.cs.meta
- Assets/Scripts/GameScene/Unit/Enemy/EnemyNormalController.cs
- Assets/Scripts/GameScene/Unit/Enemy/EnemyNormalController.cs.meta
- 敵の実装
- Playeタグがついたオブジェクトに追従する
- 敵の当たり判定
- AbstractUnitController.csを派生したクラスでStart()とUpdate()が使えないので、それの代わりのOnStartUnitController()とOnUpdateUnitController()を実装。これをoverrideすればStart()とUpdate()の代わりになる。
> Enemyの基本的なシステム実装

- Assets/Prefabs/GameScene/Enemy/Enemy.prefab
- Assets/Prefabs/GameScene/Enemy/Enemy.prefab.meta
- Assets/Prefabs/GameScene/Player/Player.prefab
- Assets/Scenes/DeveloppingScenes/UnitCollider.unity
- Assets/Scenes/DeveloppingScenes/UnitCollider.unity.meta
- Assets/Scripts/GameScene/Unit/UnitMove.cs
[Playerの動きが不自然](https://www.notion.so/tokushima-igc/Player-1df81840185380dfb169c3252b2dfdf9?pvs=4)
- とくになし
- とくになし
> fix: Unitの動きが不自然だったのを修正

- Assets/Resources/Audio/BGM/TitleScene.meta
- Assets/Resources/Audio/BGM/TitleScene/TitleBGM.mp3.meta
- Assets/Scenes/DeveloppingScenes/Target.meta
- Assets/Scenes/DeveloppingScenes/Target/April.unity
- Assets/Scenes/DeveloppingScenes/Target/April.unity.meta
- Assets/Scenes/DeveloppingScenes/UnitCollider.unity
- Assets/Scripts/Others/Audio.meta
- Assets/Scripts/Others/Audio/Audio.cs
- Assets/Scripts/Others/Audio/Audio.cs.meta
[全体をマージする](https://www.notion.so/tokushima-igc/1ce81840185380669c85cc9b8c3cfa1c?pvs=4)
- とくになし
- Aiduio用のスクリプトはSEやその他ギミックで使う予定だが今は実装していない
- とくになし
> feat: 4月分の機能のマージ

- Assets/Scenes/DeveloppingScenes/Target/April.unity
[全体をマージする](https://www.notion.so/tokushima-igc/1ce81840185380669c85cc9b8c3cfa1c?pvs=4)
なんかきれいになるらしい
- とくになし
- とくになし
> feat: カメラにPixel Perfect Cameraを設定

- .github/ISSUE_TEMPLATE/01-default.yml
> chore: issueのテンプレートを設定

- Assets/Scenes/DeveloppingScenes/Item.unity
- Assets/Scripts/GameScene/Event/AbstractEvent/AbstractEvent.cs
- Assets/Scripts/GameScene/Event/ItemEvent.cs
- Assets/Scripts/GameScene/Event/ItemEvent.cs.meta
- Assets/Scripts/GameScene/Event/eEvent.cs
- ProjectSettings/TagManager.asset
- #41 
- `OnUpdateEvent()`が抽象メソッドだったのを、定義は任意で大丈夫だと判断したので、仮想メソッドに変更した
- 繰り返し実行するイベントで終了処理がループしていたのでそれの修正
- 以下をInspector設定できる
- `ItemManager`をコンポーネント
- アイテムの種類
- アイテムを取得するイベントなのか
- とくになし
> feat: アイテムの取得イベント

- Assets/Prefabs/GameScene/Event/ItemEvent.prefab
- Assets/Scenes/GameScenes/First/1/Real/School/2F/First_1_real_class201.unity
- Assets/Scenes/GameScenes/First/1/Real/School/2F/First_1_real_class203.unity
- Assets/Scripts/GameScene/Event/ItemEvent.cs
- Assets/Scripts/GameScene/Item/ItemManager.cs
- [アイテム配置](https://www.notion.so/tokushima-igc/1e581840185380b89a18ccd4e99d0be5?pvs=4)
- #52 
- [Wiki 各オブジェクトについて](https://github.com/InnovaGameCreate/akumutogenjitsu/wiki/%E5%90%84%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6#player-tag-player)
> feat: アイテムの設置

- .github/workflows/unity-build-check.yml
> fix: ビルドチェック

- Assets/Prefabs/GameScene/Player/Player.prefab
- Assets/Scripts/GameScene/Event/AbstractEvent/AbstractEvent.cs
- Assets/Scripts/GameScene/Event/AbstractEvent/EventData.cs
- Assets/Scripts/GameScene/Event/AbstractEvent/EventData.cs.meta
- Assets/Scripts/GameScene/Event/EventManager.cs
- Assets/Scripts/GameScene/Story.meta
- Assets/Scripts/GameScene/Story/StoryManager.cs
- Assets/Scripts/GameScene/Story/StoryManager.cs.meta
- Assets/Scripts/GameScene/Unit/Player/PlayerMapMove.cs
- [ストーリーのシステム実装](https://www.notion.so/tokushima-igc/20181840185380c289c6dfa87b5209c3?source=copy_link)
- #90 
- 全てのイベントに数字を割り当てて、0の場合は常に適応され、それ以外のときは`StoryManager`が管理している数字と一致したときに適応される
- `StoryManager`が管理している数字は、初期値が1で、それを任意のタイミングで操作することができる。
- 全てのイベントには、それが終了したときに`StoryManager`が管理している数字を1上げるかを設定することができる
> ストーリーのシステム実装

- Assets/Prefabs/GameScene/EssentialObject.prefab
- Assets/Prefabs/GameScene/UI/MenuUI.prefab
- Assets/Prefabs/GameScene/UI/MenuUI.prefab.meta
- Assets/Scenes/DeveloppingScenes/UI_normal.unity
- Assets/Scripts/GameScene/Item/ItemManager.cs
- Assets/Scripts/UI/GameScene/Common/Menu.meta
- Assets/Scripts/UI/GameScene/Common/Menu/MenuController.cs
- Assets/Scripts/UI/GameScene/Common/Menu/MenuController.cs.meta
- Assets/Scripts/UI/GameScene/Common/Menu/MenuUI.cs
- Assets/Scripts/UI/GameScene/Common/Menu/MenuUI.cs.meta
- Assets/Scripts/UI/GameScene/Common/UIController.cs
- Assets/Scripts/UI/GameScene/Common/UIController.cs.meta
- [UI - メニュー画面](https://www.notion.so/tokushima-igc/UI-20181840185380599a73f5d6d8721c48?source=copy_link)
- #87
> feat: メニューのUI実装

- Assets/Scripts/GameScene/Event/AbstractEvent/AbstractEvent.cs
- Assets/Scripts/GameScene/Event/Gimmick/1/Dream/Floors2And3StairsPasswordGimmick.cs
> fix: 壁オブジェクトが消えない問題を修正

- Packages/manifest.json
- Packages/packages-lock.json
> chore: VContainerの導入

- Assets/Scripts/UI/GameScene/Common/UIController.cs
> fix: セーブ画面でXで戻れるように修正

- .github/workflows/format-check.yml
- .vscode/settings.json
- Assets/Scripts/.editorconfig
> chore: .editorconfigを設定

- Assets/Scripts/GameScene/Story/StoryManager.cs
- Assets/Scripts/GameScene/System/DateManager/DateManager.cs
> feat: 日にちがたったらストーリーレイヤーを初期化する

- Assets/Scripts/GameScene/Story/StoryManager.cs
> fix: StoryLayerの初期化方法を修正

- Assets/Scenes/GameScenes/First/1/Real/First_1_real_house.unity
- Assets/Scenes/GameScenes/First/1/Real/First_1_real_street.unity
- Assets/Scenes/GameScenes/First/1/Real/School/2F/First_1_real_class201.unity
- Assets/Scripts/GameScene/Event/EventQueue/EventQueue.cs
- [1日目現実世界のイベント実装](https://www.notion.so/tokushima-igc/1-2668184018538026bd5ee91057a79692?v=1e5818401853806e9cc7000cf67c5727&source=copy_link)
> 1日目現実世界のイベント実装

- Assets/Prefabs/GameScene/Event/Gimmick/1/Dream/CreateEntranceKeyWithMedicineEvent.prefab
- Assets/Prefabs/GameScene/Event/Gimmick/1/Dream/Floors2And3StairsPasswordGimmick.prefab
- Assets/Prefabs/GameScene/Event/PrologueEvent.prefab
- Assets/Prefabs/GameScene/Event/TextEvent.prefab
> refactor: 全てのイベントにeEventを適応する

- Assets/Resources/Image/GameScene/Player/Enemy.asset
- Assets/Resources/Image/GameScene/Player/Enemy.asset.meta
- Assets/Resources/Image/GameScene/Player/FriendA.asset
- Assets/Resources/Image/GameScene/Player/FriendA.asset.meta
- Assets/Resources/Image/GameScene/Player/FriendB.asset
- Assets/Resources/Image/GameScene/Player/FriendB.asset.meta
- Assets/Resources/Image/GameScene/Player/Narrator.asset
- Assets/Resources/Image/GameScene/Player/Narrator.asset.meta
- Assets/Scenes/GameScenes/hallway1.unity
- Assets/Scenes/GameScenes/house.unity
- Assets/Scenes/GameScenes/mapschool2.unity
- Assets/Scenes/GameScenes/scienceroom.unity
[1日目ストーリーの実装](https://www.notion.so/tokushima-igc/1-26f81840185380f68300f2dd49a3cf55?v=1e5818401853806e9cc7000cf67c5727&source=copy_link)
各マップごとのtexteventの内容
・mapschool2
textevent
化間「なんとか……撒いた…のか…？」
化間「どうして急にあいつらが…」
化間「急に夜になってるしあいつらはなんかよく分かんないやつになっちゃうしきっと夢の中だそうに違いない」
化間「とりあえず学校を出て、あれらから逃げよう」
textevent(1)
化間「なんなんだよこの壁！こんなの無かっただろ！」
化間「（やばい、思わず叫んじまった）」
化間「（あいつらもしかして耳が悪いのか？）」
化間「パスワード？これでなにか開くのか？……」
手がかりを探そう！
textevent(2)
化間「ようやくこれで一階に…」
・hallway1
textevent
鍵がかかっていて開きそうにない。
化間「………」
化間「鍵なんてどこに…」
textevent(1)
化間「鍵といえば職員室…だな」
化間「開かない…鍵がかかってるにしてもドアがびくともしない」
textevent(2)
理科室なら武器があるだろ
textevent(3)
化間「よし！これでここから…」
？？？「……ス……」　//（コロス……or…タスケテ　※どちらとも取れる）
化間「来やがった！逃げろ!!!」
・scienceroom
textevent
化間「これって鍵の形…もしかして錬成とか…」
化間「ここにあの2つを流し込めばいいんだよな」
化間「理科室にあるよな？」
textevent(1)
～奇妙な薬品Bを発見～
化間「こんなとこにあるのかよ」 …
> Texteventの追加

- Assets/Scenes/GameScenes/class101.unity
- Assets/Scenes/GameScenes/class103.unity
- Assets/Scenes/GameScenes/scienceroom.unity
https://www.notion.so/tokushima-igc/1-26f81840185380f68300f2dd49a3cf55?v=1e5818401853806e9cc7000cf67c5727&source=copy_link
- itemeventの追加
class101とclass103に薬品のeventを設置
scienceroomに鍵のeventの設置
> itemeventの追加

- Assets/Scenes/GameScenes/First/2/Dream/First_2_dream_house.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/First_2_dream_street.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_class101.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_class102.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_class103.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_class104.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_hallway1.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_scienceroom.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/1F/First_2_dream_teacherRoom.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/2F.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/2F/First_2_dream_class201.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/2F/First_2_dream_class202.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/2F/First_2_dream_class203.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/2F/First_2_dream_class204.unity.meta
- Assets/Scenes/GameScenes/First/2/Dream/School/2F/First_2_dream_hallway2.unity.meta
- Assets/Scenes/GameScenes/First/2/Real/First_2_real_house.unity.meta
- Assets/Scenes/GameScenes/First/2/Real/First_2_real_street.unity.meta
- Assets/Scenes/GameScenes/class101.unity
- Assets/Scenes/GameScenes/class103.unity
- Assets/Scenes/GameScenes/hallway1.unity
- Assets/Scenes/GameScenes/house.unity
- Assets/Scenes/GameScenes/mapschool2.unity
- Assets/Scenes/GameScenes/scienceroom.unity
eventqueueの追加
二つの薬剤を混ぜてカギにするイベントと鍵を作るやつを見つけたときのeventはまとめました。
同時に会話が出てくる流れになっているけどこれは薬剤を持っているかどうかで分岐させるということで大丈夫ですか？
> eventqueueの追加

- Assets/Scenes/GameScenes/First/1/Dream/First_1_dream_house.unity
- Assets/ScriptableObject/SceneList/SceneList.asset
- Assets/Scripts/GameScene/Event/SetDateEvent/SetDateEvent.cs
- Assets/Scripts/GameScene/System/DateManager/DateManager.cs
- Assets/UniversalRenderPipelineGlobalSettings.asset
- ProjectSettings/EditorBuildSettings.asset
> fix: バグ修正と急ぎの仕様変更

- Assets/UniversalRenderPipelineGlobalSettings.asset
> feat: 日付変更

- Assets/Scenes/StartScenes/start.unity
- Assets/UniversalRenderPipelineGlobalSettings.asset
> chore: プロジェクトの設定
